### ISSUE TITLE
Integrate nayduck tests results with Pagerduty for alerting if broken

### ISSUE THREAD

**Issue by chefsale** [near/nayduck#10] opened 2021-07-16 20:51 UTC
Currently we don't have a way to easily alert if nayduck tests are broken and revert/detect breaking changes on master. I believe we should integrate it somehow to create a Pagerduty incident and pipe it into on-fore as well. @bowenwang1996 @mina86

**Comment by mina86** [comment] 2021-07-16 20:57
That’s the end goal. We first need to get the tests to pass reliably. There’s also general issue of NayDuck having no monitoring so if workers crash for some reason we never know about it.

**Comment by chefsale** [comment] 2021-07-16 20:59
Let's maybe create an issue for interating nayduck with grafana, aka exporting machine stats via node-exporter and some sanity metrics for jobs?

**Comment by chefsale** [comment] 2021-07-16 21:00
https://github.com/near/nayduck/issues/11

**Comment by mina86** [comment] 2021-07-30 02:15
I’m gonna close this as duplicate of: https://github.com/near/nayduck/issues/4

**Closed by mina86** 2021-07-30 02:15 UTC
Labels: T-nodeX, enhancement
